-- liquibase formatted sql

-- changeset evlarus:001
CREATE TABLE addresses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_number INT,
    street     VARCHAR(255),
    city       VARCHAR(255),
    country    VARCHAR(255),
    post_code  VARCHAR(20)
);
