-- liquibase formatted sql

-- changeset evlarus:003
CREATE TABLE arrival_times (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_in  VARCHAR(10),
    check_out VARCHAR(10)
);
