-- liquibase formatted sql

-- changeset evlarus:004
CREATE TABLE hotels (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    description     VARCHAR(2000),
    brand           VARCHAR(255),
    address_id      BIGINT,
    contacts_id     BIGINT,
    arrival_time_id BIGINT,
    CONSTRAINT fk_hotel_address      FOREIGN KEY (address_id)      REFERENCES addresses(id),
    CONSTRAINT fk_hotel_contacts     FOREIGN KEY (contacts_id)     REFERENCES contacts(id),
    CONSTRAINT fk_hotel_arrival_time FOREIGN KEY (arrival_time_id) REFERENCES arrival_times(id)
);
